server:
  port: 8080
  env: "development"

database:
  host: "pg-126bf3ed-rizamertyagci-dd43.l.aivencloud.com"
  port: 25406
  user: "avnadmin"
  password: "AVNS_q6IcUYO6K9TNpZkKTKX"
  dbname: "ecommerce"
  sslmode: "require"

jwt:
  secret: "your-256-bit-secret-at-least-32-characters"
  expiryHours: 24

kafka:
  brokers:
    - "localhost:9092"
  consumerGroup: "ecommerce-group"

telemetry:
  serviceName: "ecommerce-api"
  tracingEnabled: false 