server:
  port: 8080
  env: "development"

database:
  host: "localhost"
  port: 5432
  user: "postgres"
  password: "postgres"
  dbname: "ecommerce"
  sslmode: "disable"

jwt:
  secret: "your-256-bit-secret-at-least-32-characters"
  expiryHours: 24

kafka:
  brokers:
    - "localhost:9092"
  consumerGroup: "ecommerce-group"

telemetry:
  serviceName: "ecommerce-api"
  tracingEnabled: false 